//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.22 at 08:34:09 PM KST 
//
package com.nbdf.commons.system.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for imcsConfigType complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="imcsConfigType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="allowIps" type="{http://commons.imcs/system/support}ipsField"/>
 *         &lt;element name="allowServices" type="{http://commons.imcs/system/support}imcsService"/>
 *         &lt;element name="repairServices" type="{http://commons.imcs/system/support}imcsService"/>
 *         &lt;element name="blockServices" type="{http://commons.imcs/system/support}imcsService"/>
 *         &lt;element name="serviceTime" type="{http://commons.imcs/system/support}timeField"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "imcsConfigType", propOrder = {
    "allowIps",
    "allowServices",
    "repairServices",
    "blockServices",
    "serviceTime"
})
public class ImcsConfigType {

    @XmlElement(required = true)
    protected IpsField allowIps;
    @XmlElement(required = true)
    protected ImcsService allowServices;
    @XmlElement(required = true)
    protected ImcsService repairServices;
    @XmlElement(required = true)
    protected ImcsService blockServices;
    @XmlElement(required = true)
    protected TimeField serviceTime;

    /**
     * Gets the value of the allowIps property.
     * 
     * @return
     *     possible object is
     *     {@link IpsField }
     *     
     */
    public IpsField getAllowIps() {
        return allowIps;
    }

    /**
     * Sets the value of the allowIps property.
     * 
     * @param value
     *     allowed object is
     *     {@link IpsField }
     *     
     */
    public void setAllowIps(IpsField value) {
        this.allowIps = value;
    }

    /**
     * Gets the value of the allowServices property.
     * 
     * @return
     *     possible object is
     *     {@link ImcsService }
     *     
     */
    public ImcsService getAllowServices() {
        return allowServices;
    }

    /**
     * Sets the value of the allowServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImcsService }
     *     
     */
    public void setAllowServices(ImcsService value) {
        this.allowServices = value;
    }

    /**
     * Gets the value of the repairServices property.
     * 
     * @return
     *     possible object is
     *     {@link ImcsService }
     *     
     */
    public ImcsService getRepairServices() {
        return repairServices;
    }

    /**
     * Sets the value of the repairServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImcsService }
     *     
     */
    public void setRepairServices(ImcsService value) {
        this.repairServices = value;
    }

    /**
     * Gets the value of the blockServices property.
     * 
     * @return
     *     possible object is
     *     {@link ImcsService }
     *     
     */
    public ImcsService getBlockServices() {
        return blockServices;
    }

    /**
     * Sets the value of the blockServices property.
     * 
     * @param value
     *     allowed object is
     *     {@link ImcsService }
     *     
     */
    public void setBlockServices(ImcsService value) {
        this.blockServices = value;
    }

    /**
     * Gets the value of the serviceTime property.
     * 
     * @return
     *     possible object is
     *     {@link TimeField }
     *     
     */
    public TimeField getServiceTime() {
        return serviceTime;
    }

    /**
     * Sets the value of the serviceTime property.
     * 
     * @param value
     *     allowed object is
     *     {@link TimeField }
     *     
     */
    public void setServiceTime(TimeField value) {
        this.serviceTime = value;
    }

}
