//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.12.22 at 08:34:09 PM KST 
//


package com.nbdf.commons.system.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.nbdf.commons.system.support package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _ImcsConfig_QNAME = new QName("http://commons.imcs/system/support", "imcsConfig");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.nbdf.commons.system.support
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link ImcsConfigType }
     * 
     */
    public ImcsConfigType createImcsConfigType() {
        return new ImcsConfigType();
    }

    /**
     * Create an instance of {@link ImcsService }
     * 
     */
    public ImcsService createImcsService() {
        return new ImcsService();
    }

    /**
     * Create an instance of {@link IpsField }
     * 
     */
    public IpsField createIpsField() {
        return new IpsField();
    }

    /**
     * Create an instance of {@link TimeField }
     * 
     */
    public TimeField createTimeField() {
        return new TimeField();
    }

    /**
     * Create an instance of {@link ServiceField }
     * 
     */
    public ServiceField createServiceField() {
        return new ServiceField();
    }

    /**
     * Create an instance of {@link IpField }
     * 
     */
    public IpField createIpField() {
        return new IpField();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ImcsConfigType }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://commons.imcs/system/support", name = "imcsConfig")
    public JAXBElement<ImcsConfigType> createImcsConfig(ImcsConfigType value) {
        return new JAXBElement<ImcsConfigType>(_ImcsConfig_QNAME, ImcsConfigType.class, null, value);
    }

}
